// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	FlightID     string             `json:"flight_id"`
	HotelID      string             `json:"hotel_id"`
	PaymentToken string             `json:"payment_token"`
	TotalAmount  pgtype.Numeric     `json:"total_amount"`
	Currency     string             `json:"currency"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
