// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkPendingOrderExists = `-- name: CheckPendingOrderExists :one
SELECT COUNT(*) as count
FROM orders
WHERE user_id = $1
  AND flight_id = $2
  AND hotel_id = $3
  AND status IN ('PENDING', 'FLIGHT_OK', 'HOTEL_OK')
`

type CheckPendingOrderExistsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	FlightID string      `json:"flight_id"`
	HotelID  string      `json:"hotel_id"`
}

func (q *Queries) CheckPendingOrderExists(ctx context.Context, arg CheckPendingOrderExistsParams) (int64, error) {
	row := q.db.QueryRow(ctx, checkPendingOrderExists, arg.UserID, arg.FlightID, arg.HotelID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    id,
    user_id,
    flight_id,
    hotel_id,
    payment_token,
    total_amount,
    currency,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, 'PENDING'
)
RETURNING id, user_id, flight_id, hotel_id, payment_token, total_amount, currency, status, created_at, updated_at
`

type CreateOrderParams struct {
	ID           pgtype.UUID    `json:"id"`
	UserID       pgtype.UUID    `json:"user_id"`
	FlightID     string         `json:"flight_id"`
	HotelID      string         `json:"hotel_id"`
	PaymentToken string         `json:"payment_token"`
	TotalAmount  pgtype.Numeric `json:"total_amount"`
	Currency     string         `json:"currency"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.FlightID,
		arg.HotelID,
		arg.PaymentToken,
		arg.TotalAmount,
		arg.Currency,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FlightID,
		&i.HotelID,
		&i.PaymentToken,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, flight_id, hotel_id, payment_token, total_amount, currency, status, created_at, updated_at FROM orders
WHERE id = $1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FlightID,
		&i.HotelID,
		&i.PaymentToken,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrdersByStatus = `-- name: GetOrdersByStatus :many
SELECT id, user_id, flight_id, hotel_id, payment_token, total_amount, currency, status, created_at, updated_at FROM orders
WHERE status = $1
ORDER BY created_at ASC
LIMIT $2 OFFSET $3
`

type GetOrdersByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) GetOrdersByStatus(ctx context.Context, arg GetOrdersByStatusParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FlightID,
			&i.HotelID,
			&i.PaymentToken,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrdersByUserID = `-- name: GetOrdersByUserID :many
SELECT id, user_id, flight_id, hotel_id, payment_token, total_amount, currency, status, created_at, updated_at FROM orders
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetOrdersByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) GetOrdersByUserID(ctx context.Context, arg GetOrdersByUserIDParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrdersByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FlightID,
			&i.HotelID,
			&i.PaymentToken,
			&i.TotalAmount,
			&i.Currency,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderPaymentToken = `-- name: UpdateOrderPaymentToken :one
UPDATE orders
SET 
    payment_token = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, flight_id, hotel_id, payment_token, total_amount, currency, status, created_at, updated_at
`

type UpdateOrderPaymentTokenParams struct {
	ID           pgtype.UUID `json:"id"`
	PaymentToken string      `json:"payment_token"`
}

func (q *Queries) UpdateOrderPaymentToken(ctx context.Context, arg UpdateOrderPaymentTokenParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderPaymentToken, arg.ID, arg.PaymentToken)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FlightID,
		&i.HotelID,
		&i.PaymentToken,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET 
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, flight_id, hotel_id, payment_token, total_amount, currency, status, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FlightID,
		&i.HotelID,
		&i.PaymentToken,
		&i.TotalAmount,
		&i.Currency,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
