// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckPendingOrderExists(ctx context.Context, arg CheckPendingOrderExistsParams) (int64, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrdersByStatus(ctx context.Context, arg GetOrdersByStatusParams) ([]Order, error)
	GetOrdersByUserID(ctx context.Context, arg GetOrdersByUserIDParams) ([]Order, error)
	UpdateOrderPaymentToken(ctx context.Context, arg UpdateOrderPaymentTokenParams) (Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
